
--ALTER TABLE PRESCRIZIONE DROP CONSTRAINT FK_ANAG_ID;

--ALTER TABLE PRESCRIZIONE DROP CONSTRAINT FK_ITEM_ID;


--DROP TABLE ANAGRAFICA;

CREATE MEMORY TABLE ANAGRAFICA (
  ID INTEGER IDENTITY PRIMARY KEY,
  NOME VARCHAR(256) NOT NULL,
  COGNOME VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NULL
);

--DROP TABLE ITEM_MAGAZZINO;

CREATE MEMORY TABLE ITEM_MAGAZZINO (
  ID INTEGER IDENTITY PRIMARY KEY,
  NOME VARCHAR(256) NOT NULL,
  QUANTITA INTEGER NOT NULL,
  SOGLIA INTEGER NOT NULL
);

--DROP TABLE PRESCRIZIONE;

CREATE MEMORY TABLE PRESCRIZIONE (
  ID INTEGER IDENTITY PRIMARY KEY,
  ANAGRAFICA_ID INTEGER NOT NULL,
  ITEM_ID INTEGER NOT NULL,
  USERNAME VARCHAR(256) NOT NULL,
  QUANTITA INTEGER NOT NULL
);

ALTER TABLE PRESCRIZIONE ADD CONSTRAINT FK_ANAG_ID FOREIGN KEY(ANAGRAFICA_ID) REFERENCES ANAGRAFICA(ID); 

ALTER TABLE PRESCRIZIONE ADD CONSTRAINT FK_ITEM_ID FOREIGN KEY(ITEM_ID) REFERENCES ITEM_MAGAZZINO(ID);

